/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: { "2xl": "1600px" },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        brand: {
          orange: "#FF5A1F",
          orangeDark: "#DE4713",
          orangeLight: "#FF7A47",
          charcoal: "#1B1F28",
          charcoalDeep: "#0E1116",
          charcoalSoft: "#2A3039",
          cream: "#FAF6F0",
          creamDeep: "#F0E8DB",
          ink: "#0E1116",
          paper: "#FFFFFF",
          gray: "#6B7280",
          grayLight: "#F3F4F6",
          navy: "#1B1F28",
          navyDeep: "#0E1116",
          navySoft: "#2A3039",
          red: "#FF5A1F",
          redDark: "#DE4713",
          yellow: "#FF5A1F",
          yellowDark: "#DE4713",
          black: "#0E1116",
          blueDeep: "#1B1F28",
          blue: "#FF5A1F",
          blueLight: "#FF7A47",
          blueTint: "#FFF1EA",
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ['"DM Serif Display"', '"Playfair Display"', "Georgia", "serif"],
        grotesk: ['"Space Grotesk"', "Inter", "system-ui", "sans-serif"],
      },
      letterSpacing: { tightest: "-0.035em" },
      boxShadow: {
        soft: "0 24px 70px -22px rgba(14,17,22,0.30)",
        card: "0 1px 2px rgba(14,17,22,0.05), 0 8px 28px -10px rgba(14,17,22,0.12)",
        orange: "0 24px 60px -20px rgba(255,90,31,0.55)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        marquee: { "0%": { transform: "translateX(0%)" }, "100%": { transform: "translateX(-50%)" } },
        "heat-pulse": { "0%, 100%": { opacity: "0.4" }, "50%": { opacity: "0.7" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        marquee: "marquee 35s linear infinite",
        "heat-pulse": "heat-pulse 3s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
